openapi: 3.0.0
servers: []
info:
  version: 0.1.6
  title: Node API
paths:
  /events/stream:
    get:
      summary: Get an event stream
      description: The connection will be upgraded to use the websocket protocol.
      parameters:
        - name: ack
          in: query
          required: false
          description: When specified, client MUST ack (empty reply) each message before server will send another.
            This enables the client to apply back pressure to the stream
          schema:
            type: boolean
          allowEmptyValue: true
        - name: since
          in: query
          description: Filters events to those occurring on/after the provided instant
          required: false
          schema:
            type: string
            format: date-time
          explode: false
        - name: roots
          in: query
          description: Filters events to those w/ the provided root op ids
          required: false
          schema:
            type: array
            items:
              type: string
          explode: false
      tags:
        - events
      responses:
        '101':
          description: HTTP/1.1 ["Switching Protocols" response status code](https://tools.ietf.org/html/rfc7231#section-6.2.2)
          headers:
            Upgrade:
              schema:
                type: string
                enum:
                  - websocket
            Connection:
              schema:
                type: string
                enum:
                  - Upgrade
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
        '400':
          description: HTTP/1.1 ["Bad Request" response status code](https://tools.ietf.org/html/rfc7231#section-6.5.1)
  /liveness:
    get:
      summary: Get liveness of node
      tags:
        - liveness
      responses:
        '200':
          description: HTTP/1.1 ["OK" response status code](https://tools.ietf.org/html/rfc7231#section-6.3.1)
        '500':
          description: HTTP/1.1 ["Internal Server Error" response status code](https://tools.ietf.org/html/rfc7231#section-6.6.1)
  /ops/starts:
    post:
      summary: Starts an op
      tags:
        - ops
      responses:
        '201':
          description: HTTP/1.1 ["Created" response status code](https://tools.ietf.org/html/rfc7231#section-6.3.2)
          content:
            text/plain:
              schema:
                description: 'The id of the [started] op'
                type: string
        '400':
          description: HTTP/1.1 ["Bad Request" response status code](https://tools.ietf.org/html/rfc7231#section-6.5.1)
        '500':
          description: HTTP/1.1 ["Internal Server Error" response status code](https://tools.ietf.org/html/rfc7231#section-6.6.1)
      requestBody:
        content:
          application/json:
            schema:
              required:
                - pkg
              properties:
                args:
                  type: object
                  description: arguments passed to the op to satisfy inputs
                  additionalProperties:
                    $ref: '#/components/schemas/Value'
                pkg:
                  required:
                    - ref
                  properties:
                    ref:
                      type: string
                      format: uri-reference
                      description: reference to a pkg
                    pullCreds:
                      description: credentials used during authentication with the source of the package
                      required:
                        - username
                        - password
                      properties:
                        username:
                          type: string
                        password:
                          type: string
                      type: object
                  type: object
              type: object
        required: true
  /ops/kills:
    post:
      summary: Kills an op
      tags:
        - ops
      responses:
        '204':
          description: HTTP/1.1 ["No Content" response status code](https://tools.ietf.org/html/rfc7231#section-6.3.5)
        '400':
          description: HTTP/1.1 ["Bad Request" response status code](https://tools.ietf.org/html/rfc7231#section-6.5.1)
        '500':
          description: HTTP/1.1 ["Internal Server Error" response status code](https://tools.ietf.org/html/rfc7231#section-6.6.1)
      requestBody:
        content:
          application/json:
            schema:
              required:
                - opId
              properties:
                opId:
                  type: string
              type: object
        required: true
  '/pkgs/{ref}/contents':
    get:
      summary: Lists package contents
      tags:
        - pkgs
      parameters:
        - name: ref
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: HTTP/1.1 ["OK" response status code](https://tools.ietf.org/html/rfc7231#section-6.3.1)
          headers:
            Content-Length:
              description: HTTP/1.1 ["Content-Length" header field](https://tools.ietf.org/html/rfc7230#section-3.3.2)
              schema:
                type: integer
          content:
            application/json:
              schema:
                items:
                  properties:
                    path:
                      description: absolute path within pkg
                      type: string
                    size:
                      type: integer
                    mode:
                      description: golang [FileMode](https://golang.org/pkg/os/#FileMode)
                      type: integer
                type: array
        '400':
          description: HTTP/1.1 ["Bad Request" response status code](https://tools.ietf.org/html/rfc7231#section-6.5.1)
        '401':
          description: HTTP/1.1 ["Unauthorized" response status code](https://tools.ietf.org/html/rfc7235#section-3.1)
        '403':
          description: HTTP/1.1 ["Forbidden" response status code](https://tools.ietf.org/html/rfc7231#section-6.5.3)
        '404':
          description: HTTP/1.1 ["Not Found" response status code](https://tools.ietf.org/html/rfc7231#section-6.5.4)
        '500':
          description: HTTP/1.1 ["Internal Server Error" response status code](https://tools.ietf.org/html/rfc7231#section-6.6.1)
  '/pkgs/{ref}/contents/{path}':
    get:
      summary: Gets pkg content at path
      tags:
        - pkgs
      parameters:
        - name: ref
          in: path
          required: true
          schema:
            type: string
        - name: path
          in: path
          required: true
          schema:
            type: string
        - name: Range
          description: HTTP/1.1 ["Range" header field](https://tools.ietf.org/html/rfc7233#section-3.1)
          in: header
          required: false
          schema:
            type: string
      responses:
        '200':
          description: HTTP/1.1 ["OK" response status code](https://tools.ietf.org/html/rfc7231#section-6.3.1)
          headers:
            Accept-Ranges:
              description: HTTP/1.1 ["Accept-Ranges" header field](https://tools.ietf.org/html/rfc7233#section-2.3)
              schema:
                type: string
                enum:
                  - bytes
            Content-Length:
              description: HTTP/1.1 ["Content-Length" header field](https://tools.ietf.org/html/rfc7230#section-3.3.2)
              schema:
                type: integer
          content:
            application/octet-stream: {}
            multipart/byteranges: {}
            text/plain: {}
            application/json: {}
        '206':
          description: HTTP/1.1 ["Partial Content" response status code](https://tools.ietf.org/html/rfc7233#section-4.1)
          headers:
            Content-Length:
              description: HTTP/1.1 ["Content-Length" header field](https://tools.ietf.org/html/rfc7230#section-3.3.2)
              schema:
                type: integer
            Content-Range:
              description: HTTP/1.1 ["Content-Range" header field](https://tools.ietf.org/html/rfc7233#section-4.2)
              schema:
                type: string
          content:
            application/octet-stream:
              schema:
                type: string
            multipart/byteranges:
              schema:
                type: string
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
        '401':
          description: HTTP/1.1 ["Unauthorized" response status code](https://tools.ietf.org/html/rfc7235#section-3.1)
        '403':
          description: HTTP/1.1 ["Forbidden" response status code](https://tools.ietf.org/html/rfc7231#section-6.5.3)
        '404':
          description: HTTP/1.1 ["Not Found" response status code](https://tools.ietf.org/html/rfc7231#section-6.5.4)
        '416':
          description: HTTP/1.1 ["Range Not Satisfiable" response status code](https://tools.ietf.org/html/rfc7233#section-4.4)
        '500':
          description: HTTP/1.1 ["Internal Server Error" response status code](https://tools.ietf.org/html/rfc7231#section-6.6.1)
    head:
      summary: Gets pkg content at path
      tags:
        - pkgs
      parameters:
        - name: ref
          in: path
          required: true
          schema:
            type: string
        - name: path
          in: path
          required: true
          schema:
            type: string
        - name: Range
          description: HTTP/1.1 ["Range" header field](https://tools.ietf.org/html/rfc7233#section-3.1)
          in: header
          required: false
          schema:
            type: string
      responses:
        '200':
          description: HTTP/1.1 ["OK" response status code](https://tools.ietf.org/html/rfc7231#section-6.3.1)
          headers:
            Accept-Ranges:
              description: HTTP/1.1 ["Accept-Ranges" header field](https://tools.ietf.org/html/rfc7233#section-2.3)
              schema:
                type: string
                enum:
                  - bytes
            Content-Length:
              description: HTTP/1.1 ["Content-Length" header field](https://tools.ietf.org/html/rfc7230#section-3.3.2)
              schema:
                type: integer
        '206':
          description: HTTP/1.1 ["Partial Content" response status code](https://tools.ietf.org/html/rfc7233#section-4.1)
          headers:
            Content-Length:
              description: HTTP/1.1 ["Content-Length" header field](https://tools.ietf.org/html/rfc7230#section-3.3.2)
              schema:
                type: integer
            Content-Range:
              description: HTTP/1.1 ["Content-Range" header field](https://tools.ietf.org/html/rfc7233#section-4.2)
              schema:
                type: string
          content:
            application/octet-stream:
              schema:
                type: string
            multipart/byteranges:
              schema:
                type: string
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
        '401':
          description: HTTP/1.1 ["Unauthorized" response status code](https://tools.ietf.org/html/rfc7235#section-3.1)
        '403':
          description: HTTP/1.1 ["Forbidden" response status code](https://tools.ietf.org/html/rfc7231#section-6.5.3)
        '404':
          description: HTTP/1.1 ["Not Found" response status code](https://tools.ietf.org/html/rfc7231#section-6.5.4)
        '416':
          description: HTTP/1.1 ["Range Not Satisfiable" response status code](https://tools.ietf.org/html/rfc7233#section-4.4)
        '500':
          description: HTTP/1.1 ["Internal Server Error" response status code](https://tools.ietf.org/html/rfc7231#section-6.6.1)
components:
  schemas:
    Value:
      description: a typed value
      oneOf:
        - properties:
            array:
              type: array
        - properties:
            dir:
              description: path
              type: string
        - properties:
            file:
              description: path
              type: string
        - properties:
            number:
              type: number
        - properties:
            object:
              type: object
        - properties:
            socket:
              description: socket address
              type: string
        - properties:
            string:
              type: string
      type: object
    Event:
      properties:
        timestamp:
          type: string
          format: dateTime
      oneOf:
        - properties:
            containerExited:
              $ref: '#/components/schemas/ContainerExitedEvent'
        - properties:
            containerStarted:
              $ref: '#/components/schemas/ContainerStartedEvent'
        - properties:
            containerStdErrWrittenTo:
              $ref: '#/components/schemas/ContainerStdErrWrittenToEvent'
        - properties:
            containerStdOutWrittenTo:
              $ref: '#/components/schemas/ContainerStdOutWrittenToEvent'
        - properties:
            opEnded:
              $ref: '#/components/schemas/OpEndedEvent'
        - properties:
            opStarted:
              $ref: '#/components/schemas/OpStartedEvent'
        - properties:
            opErred:
              $ref: '#/components/schemas/OpErredEvent'
        - properties:
            parallelCallEnded:
              $ref: '#/components/schemas/ParallelCallEndedEvent'
        - properties:
            serialCallEnded:
              $ref: '#/components/schemas/SerialCallEndedEvent'
      type: object
    ContainerExitedEvent:
      properties:
        imageRef:
          type: string
        exitCode:
          type: integer
        rootOpId:
          type: string
        containerId:
          type: string
        pkgRef:
          type: string
        outputs:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/Value'
      type: object
    ContainerStartedEvent:
      properties:
        imageRef:
          type: string
        rootOpId:
          type: string
        containerId:
          type: string
        pkgRef:
          type: string
      type: object
    ContainerStdErrWrittenToEvent:
      properties:
        imageRef:
          type: string
        data:
          type: string
          format: binary
        rootOpId:
          type: string
        containerId:
          type: string
        pkgRef:
          type: string
      type: object
    ContainerStdOutWrittenToEvent:
      properties:
        imageRef:
          type: string
        data:
          type: string
          format: binary
        rootOpId:
          type: string
        containerId:
          type: string
        pkgRef:
          type: string
      type: object
    OpErredEvent:
      properties:
        rootOpId:
          type: string
        msg:
          type: string
        opId:
          type: string
        pkgRef:
          type: string
      type: object
    OpEndedEvent:
      properties:
        rootOpId:
          type: string
        opId:
          type: string
        pkgRef:
          type: string
        outcome:
          enum:
            - SUCCEEDED
            - FAILED
            - KILLED
          type: string
        outputs:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/Value'
      type: object
    OpStartedEvent:
      properties:
        rootOpId:
          type: string
        opId:
          type: string
        pkgRef:
          type: string
      type: object
    ParallelCallEndedEvent:
      properties:
        rootOpId:
          type: string
        callId:
          type: string
      type: object
    SerialCallEndedEvent:
      properties:
        rootOpId:
          type: string
        callId:
          type: string
        outputs:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/Value'
      type: object
